### ISSUE TITLE
ClassLoader NullPointerException when loading NioReadOnlyRandomAccessFile in consoles/shells

### ISSUE THREAD

**Issue by ryan-williams** [tomwhite/hdf5-java-cloud#1]
trying to work through [`10x_hdf5_to_parquet.scala`](https://github.com/tomwhite/hdf5-java-cloud/blob/8bbf996eb3b646b08b35f4a43e8a953b24307c5c/10x_hdf5_to_parquet.scala), and seeing a weird error:

```scala
import hammerlab.path._
import com.tom_e_white.hdf5_java_cloud.NioReadOnlyRandomAccessFile
val file = "files/1M_neurons_filtered_gene_bc_matrices_h5.h5"
val path = Path(file)
new NioReadOnlyRandomAccessFile(path)
```
```
java.lang.NullPointerException
  at scala.runtime.ScalaRunTime$.replStringOf(ScalaRunTime.scala:264)
  at .$print$lzycompute(<console>:16)
  at .$print(<console>:6)
  at $print(<console>)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:735)
  at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:999)
  at scala.tools.nsc.interpreter.IMain.$anonfun$interpret$1(IMain.scala:567)
  at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:34)
  at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:30)
  at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:33)
  at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:566)
  at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:593)
  at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:563)
  at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:886)
  at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:754)
  at scala.tools.nsc.interpreter.ILoop.processLine(ILoop.scala:456)
  at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:477)
  at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:1069)
  at xsbt.ConsoleInterface.run(ConsoleInterface.scala:72)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at sbt.internal.inc.AnalyzingCompiler.call(AnalyzingCompiler.scala:237)
  at sbt.internal.inc.AnalyzingCompiler.console(AnalyzingCompiler.scala:199)
  at sbt.Console.console0$1(Console.scala:43)
  at sbt.Console.$anonfun$apply$2(Console.scala:46)
  at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
  at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
  at sbt.TrapExit$App.run(TrapExit.scala:252)
  at java.lang.Thread.run(Thread.java:745)
```

I see this when I run in `spark-shell`, via `scala -cp target/hdf5-java-cloud-0.0.1-SNAPSHOT.jar`, or in `sbt console` (after adapting the build to SBT in [this branch](https://github.com/ryan-williams/hdf5-java-cloud/tree/sbt)).

The tests get through [an equivalent line](https://github.com/tomwhite/hdf5-java-cloud/blob/8bbf996eb3b646b08b35f4a43e8a953b24307c5c/src/test/java/com/tom_e_white/hdf5_java_cloud/NioReadOnlyRandomAccessFileTest.java#L17) ok, and I'm able to run those fine via `maven test` or `sbt test`.

The only good hit I see on the internet is [this post](https://groups.google.com/forum/#!topic/jpmml/6lMevl8MpIA), where the best lead seems to be about a shading misconfiguration, but I don't think that's what's happening here; in particular, `sbt console` builds its classpath from the raw class files, and doesn't go through any shading.

It seems that it's either:

1. a classloader issue of some kind, though I don't understand why it's working for you via spark-shell, but not for me, or
2. something to do with the way I built `edu.ucar:cdm:5.0.0-SNAPSHOT` from you fork.

For 2., I [added the `maven-publish` gradle plugin](https://github.com/ryan-williams/thredds/commit/ad6df1c1585782f24e819f3837c18bc02680866a) and ran `./gradlew :cdm:PublishToMavenLocal`; maybe that built that JAR differently than whatever you did / what was supposed to happen?

**Comment by tomwhite** [comment]
Very odd. The Maven build uses the shade plugin to build a fat jar, but doesn't do any class relocation, and as you said your sbt build doesn't do any shading at all.

I've uploaded the jar file so you can see if it works for you (to eliminate #2): https://s3.amazonaws.com/tomwhite/tmp/hdf5-java-cloud-0.0.1-SNAPSHOT.jar

Another guess - could it be that the NPE is coming from `RandomAccessFile#toString()` being null (since the location is not set). If you override `NioReadOnlyRandomAccessFile#toString()` does it help? (Perhaps gives a better underlying error?)

FWIW the version of Spark, Scala, and Java I'm using is as follows - what versions do you have?

```bash
% spark-shell --version
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /___/ .__/\_,_/_/ /_/\_\   version 2.2.1
      /_/
                        
Using Scala version 2.11.8, Java HotSpot(TM) 64-Bit Server VM, 1.8.0_171
Branch 
Compiled by user felixcheung on 2017-11-24T23:19:45Z
Revision 
Url 
Type --help for more information.
```

**Comment by tomwhite** [comment]
I just reproduced and tried the `toString` fix, which worked! Please let me know if it works for you too: https://github.com/tomwhite/hdf5-java-cloud/commit/90c89d34b0aa2d7d64fc5523f0b94a59fa0101f2

**Comment by ryan-williams** [comment]
Wow, great catch! So that is a symptom of an object's `toString` returning `null` when the repl is trying to display that object as the returned value from a statement…? Very strange. Would have expected it to just display `null` 🤔 Anyway, that seems to fix it, thanks a lot!
